name: hello-world3
on: 
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow
      uses: ./.github/workflows/hello-world2.yml

    # List all github environment variables
    - name: List all github envrioment variables
      run: env | grep GITHUB_ENV
              
