# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      output1:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      output2:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
      - id: step0
        run: echo "${{ inputs.input1 }}"
      - id: step1
        run: echo "output1=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "output2=world" >> $GITHUB_OUTPUT
