# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from the reusable workflow!"
